trying rasterio/fiona way of handling travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,62 +1,85 @@
-language: python
-python:
-  - "3.7"
-  - "3.8"
-install:
-  - sudo apt-get update
-  # We do this conditionally because it saves us some downloading if the
-  # version is the same.
-  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
-      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
-    else
-      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
-    fi
-  - bash miniconda.sh -b -p $HOME/miniconda
-  - source "$HOME/miniconda/etc/profile.d/conda.sh"
-  - hash -r
-  - conda config --set always_yes yes --set changeps1 no
-  - conda update -q conda
-  # Useful for debugging any issues with conda
-  - conda info -a
+dist: xenial
 
-  # Replace dep1 dep2 ... with your dependencies
-  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
-  - conda activate test-environment
-  - conda install gdal
-  - pip install -r requirements.txt
-  - pip install pytest
-# command to run tests
-script:
-  - python setup.py install
-  - pytest
+language: python
+
+env:
+  global:
+    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
+    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
+    - GDALINST=$HOME/gdalinstall
+    - GDALBUILD=$HOME/gdalbuild
+    - PROJINST=$HOME/gdalinstall
+    - PROJBUILD=$HOME/projbuild
 
 jobs:
   include:
-    - stage: coverage
-      python: "3.8"
-      install:
-        - sudo apt-get update
-        # We do this conditionally because it saves us some downloading if the
-        # version is the same.
-        - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
-            wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
-          else
-            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
-          fi
-        - bash miniconda.sh -b -p $HOME/miniconda
-        - source "$HOME/miniconda/etc/profile.d/conda.sh"
-        - hash -r
-        - conda config --set always_yes yes --set changeps1 no
-        - conda update -q conda
-        # Useful for debugging any issues with conda
-        - conda info -a
+    - python: "3.6"
+      env:
+        GDALVERSION="2.3.3"
+        PROJVERSION="4.9.3"
+    - python: "3.6"
+      env:
+        GDALVERSION="2.4.4"
+        PROJVERSION="4.9.3"
+    - python: "3.7"
+      env:
+        GDALVERSION="2.4.4"
+        PROJVERSION="4.9.3"
+    - python: "3.8"
+      env:
+        GDALVERSION="2.4.4"
+        PROJVERSION="4.9.3"
+    - python: "3.6"
+      env:
+        GDALVERSION="3.0.4"
+        PROJVERSION="6.2.1"
+    - python: "3.7"
+      env:
+        GDALVERSION="3.0.4"
+        PROJVERSION="6.2.1"
+    - python: "3.8"
+      env:
+        GDALVERSION="3.0.4"
+        PROJVERSION="6.2.1"
+    - python: "3.8"
+      env:
+        GDALVERSION="master"
+        PROJVERSION="6.2.1"
+  allow_failures:
+    - env:
+        GDALVERSION="master"
+        PROJVERSION="6.2.1"
 
-        # Replace dep1 dep2 ... with your dependencies
-        - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
-        - conda activate test-environment
-        - conda install gdal
-        - pip install -r requirements.txt
-        - pip install pytest pytest-cov coveralls
-      script: pytest --cov-config=.coveragerc --cov=rivgraph/
-      after_success:
-        - coveralls
+addons:
+  apt:
+    packages:
+    - libhdf5-serial-dev
+    - libgdal-dev
+    - libatlas-dev
+    - libatlas-base-dev
+    - gfortran
+
+before_install:
+  - python -m pip install -U pip
+  - python -m pip install wheel
+  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
+  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
+  - . ./scripts/travis_proj_install.sh
+  - travis_wait 20 . ./scripts/travis_gdal_install.sh
+  - export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal
+  - export PROJ_LIB=$GDALINST/gdal-$GDALVERSION/share/proj
+
+install:
+  - "if [ \"$GDALVERSION\" == \"master\" -o $(gdal-config --version) == \"$GDALVERSION\" ]; then echo \"Using gdal $GDALVERSION\"; else echo \"NOT using gdal $GDALVERSION as expected; aborting\"; exit 1; fi"
+  - "python -m pip install -r requirements.txt"
+  - "GDAL_CONFIG=$GDALINST/gdal-$GDALVERSION/bin/gdal-config python -m pip install --no-deps --force-reinstall --no-use-pep517 -e ."
+  - "python -m pip install pytest"
+  - "python -m pip install coveralls>=1.1"
+
+script:
+  - python setup.py install
+  - pytest
+  - pytest --cov-config=.coveragerc --cov=rivgraph/
+
+after_success:
+  - coveralls
